### ISSUE TITLE
Devkit - website

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#10]
## Overview

English description of goal in a sentence or two, usually in the form of a user story.

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- List any assumptions that
- You are making in terms of time-frame,
- Output, or general context setting

### Acceptance

- List of what needs to be true
- to consider this done
- done done

## Tasks

- [ ] A list of tasks that need
- [ ] to be done to call this issue done

**Comment by tjchmielewski** [comment]
To tell a solid story and paint a clear picture of how bootleg could work and supply some initial code to inspire and enable folks to make this story a reality.

Q. What inspires and enables entrepreneurs and developers? How do we reach them? How do we know if it helped anyone get their business started? 

Assumptions: Making a useful, well-thought-out, cleanly coded "devkit" will help the Web3 community see this new vision of the web and persuade them to take action. 

Acceptance: Having something to get feedback if it's helping the community or just "meh" or how we can improve upon it. (obviously not great at writing acceptance criteria)

Tasks: Content Strategy, Site Architecture, Copy, Wireframe, Interaction Design, UI Design, User Testing

**Comment by barlock** [comment]
Dupe of #12
