### ISSUE TITLE
Provide encrypted video with access control

### ISSUE THREAD

**Issue by hadasz** [ConsenSys/web3studio-bootleg#107]
## Overview

As a video provider - I want to provide my clients (and only my clients) with an encrypted video

### Reference
**Goal**:Provide access to encrypted video with access control (so only to authorized people)
**Server Side**:
Encrypt video with AES in CBC mode, so only one artifact is needed for decryption
Retrieve public keys of all token owners from smart contract
Client will send an API request that includes a signature. Server verifies that the signature came from the correct private key
Upon verification, server sends location of video, along with private key (both items are encrypted with users public key)
**Client Side**:
Send API request to server that includes an ECDSA signature with Ethereum private key.
Fetch and decrypt video
### Questions

Can we use AWS for the encryption and access control?
### Assumptions

- List any assumptions that
- You are making in terms of time-frame,
- Output, or general context setting

### Acceptance

-An end to end system that allows a server to give each authorized client an encrypted video

## Tasks

-investigate how AWS could be used for this
-Build server side code
-build CLI
-end to end tests

**Comment by breakpointer** [comment]
Done? https://github.com/ConsenSys/web3studio-bootleg/tree/master/packages/aws-cli-encrypt
