### ISSUE TITLE
Investigate AWS cryptography offerings

### ISSUE THREAD

**Issue by hadasz** [ConsenSys/web3studio-bootleg#108]
## Overview

As developers, we want a sense of how to easily deploy an end to end encryption scheme

### Reference

https://aws.amazon.com/blogs/security/how-to-encrypt-and-decrypt-your-data-with-the-aws-encryption-cli/

### Questions

- AES encryption is possible
-Would access control via ethereum addresses be possible?

### Assumptions

- AWS CLI can be used
- Scripts can be written in bash or python

### Acceptance

- A simple example of how to encrypt/decrypt a file with AWS CLI locally (symmetric encryption)
- A simple example of how to encrypt/decrypt a file from S3 (also symmetric encryption)
- Look into how to use KMS to manage master key for file
-Script that gives out signed url's based on Ethereum address

**Comment by hadasz** [comment]
Federated Users - users outside of AWS 
-S3 bucket with client side encryption

**Comment by hadasz** [comment]
Cryptographic Materials Manager - https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/concepts.html#crypt-materials-manager
-Can create a custom one
-Perhaps this is where Ethereum addresses could be integrated in

**Comment by hadasz** [comment]
Use Amazon CloudFront with s3 buckets
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AmazonCloudFront_DevGuide.pdf
-via URLS - which are signed with asymmetric key pairs

**Comment by barlock** [comment]
My understanding of signed urls is that they're for inter-account communication rather than distribution. 

I believe we could use them in-tandem with a [lambda authorizor](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html) for the download.

**Comment by hadasz** [comment]
This description makes it seem like it is for anyone - not just for inter-account communication
https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html

I also know that CLoudFront has signed urls for people outside of AWS - so I was assuming it was similar for s3 buckets

**Comment by barlock** [comment]
Oh interesting! I like the time-based thing too. I believe I was thinking about cloudfront signed urls (?), namespace overload is challenging.

**Comment by hadasz** [comment]
Architecture: 
One time Things that need to be tested and put into a script:
-Use AWS-CLI-Encryption to encrypt video
-Deploy video to s3
-generate pre-signed url for access
-store key

**Server Side**
-Has private key and pre-signed URL
-Upon request from client, checks if public key of client is a public key of a token holder via smart contract
-If so, check that signature of client holds up
-If so - encrypt private key and url and send them both to client

**Client Side**
-Light wrapper around aws-cli that gets video from s3 using presigned url, downloads and decrypts it

**Comment by breakpointer** [comment]
Looks good to me! So for storing the key and url, what should we do there? A simple RDS Mysql instance?

**Comment by hadasz** [comment]
Actually was about to slack y’all about that. I found something called AWS secrets that you can access from lambda functions. Looks like just a password protected database, but have either of you had experience with it?

**Comment by hadasz** [comment]
As for the signature - it will be sent along with the public key. Only the public key and the signature are needed to verify that the signature is valid and came from the correct person. Then server just needs to access smart contract o see if public key is the address of a token holder

**Comment by hadasz** [comment]
Haskell AWS Lambda for public key cryptography aspect (access control) https://github.com/seek-oss/serverless-haskell
Ruby AWS Lambda for interacting with S3 (only specific languages have client-side encryption capabilities)
