### ISSUE TITLE
Bootleg DevKit Introduction

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#23]
## As Deborah the developer, I just found my way into the Bootleg devKit webpage (friend told me about the article and I clicked the link), I need to know within 15 seconds whether this is something I really care enough to continue learning about, so that I can take the next step and start reading the details.

English description of goal in a sentence or two, usually in the form of a user story.

### Questions

- What does a canonical Deborah really care about?

- Will Deborah likely go on to read the stuff in one sitting, or should we anticipate that she might set it aside for a while and we need a way to prompt her back into the devKit...maybe a signup, alert? Something clever we can use for all devKits and other content we want to be sure people don't forget to come back to?

### Assumptions

- Deborah is 

### Acceptance

- Most Deborahs continue to read into the rest of the devKit

## Tasks

- [ ] Write draft of Intro (JW)
- [ ] Review and compose Intro into web page (?)

**Comment by barlock** [comment]
Copy of #87
