### ISSUE TITLE
SXSW Audition Pitch

### ISSUE THREAD

**Issue by humbitious** [ConsenSys/web3studio-bootleg#26]
## Tasks

- [x] Create a slide deck (Outline, Copy, Slide Creation, Illustrations and/or Photo gathering, Animation

**Comment by barlock** [comment]
Deadline Jan 31

**Comment by humbitious** [comment]
https://docs.google.com/presentation/d/1irGBcMS7XjZWcXNfKXFlxAUZ0POn7cThBGgXaZNmSDU/edit#slide=id.p39

Not putting ConsenSys internal deck on public repo, but web3studio team should be able to get to link.

**Comment by humbitious** [comment]
Here is the final piece for review and delivery: https://docs.google.com/presentation/d/1irGBcMS7XjZWcXNfKXFlxAUZ0POn7cThBGgXaZNmSDU/edit#slide=id.p1

**Comment by barlock** [comment]
Re-opening to give the team a chance to review during demo.
