### ISSUE TITLE
Review existing ERCs

### ISSUE THREAD

**Issue by breakpointer** [ConsenSys/web3studio-bootleg#27]
## Overview

As an ERC designer, so I understand how ERCs are structured review existing ERCs and how they are defined. 

### Reference
-[EIP20 document](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md)
-[OpenZeppelin ERC](
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/9b3710465583284b8c4c5d2245749246bb2e0094/contracts/token/ERC20/ERC20.sol)
-[From Consensys, EIP20](https://github.com/ConsenSys/Tokens/blob/fdf687c69d998266a95f15216b1955a4965a0a6d/contracts/eip20/EIP20.sol)

### Assumptions
- Timeboxed Sizing

### Acceptance

- Produce a ~list~ diagram of ERCs that are similar/could be used for PIB/bootleg

**Comment by breakpointer** [comment]
This is an interesting one https://blog.enjincoin.io/erc-1155-the-crypto-item-standard-ac9cf1c5a226

You can mint crypto items https://mint.enjin.io/

**Comment by breakpointer** [comment]
Thanks to this article there are a few more ERCS to review
https://medium.com/@OpenLawOfficial/modernizing-art-with-blockchains-6cba4694833d

https://github.com/ethereum/EIPs/issues/888
https://github.com/ethereum/EIPs/issues/998
https://github.com/ethereum/eips/issues/1155

**Comment by breakpointer** [comment]
I drawed a drawing https://www.lucidchart.com/invitations/accept/2b383749-a557-478f-a0e2-f3ee008e4af2

**Comment by barlock** [comment]
Could you add a rough 1-sentence description of all of the ERC's referenced? I'm not sure what multi-dimensional means in this context.

I'm also curious which ERCs you considered and throw out and why (1155 comes to mind).

**Comment by breakpointer** [comment]
Thanks for the feedback. To be clear, nothing has been thrown out. Thrown out, in my mind, means explicitly would not work. ERC 1155 may well fit into the fractional owner functional block in some way. I'll note it there. 

I'll also add a short index of ERC numbers and their simple summary to my write up.

**Comment by breakpointer** [comment]
Here's a draft of the ERC glossary:


ERC-721 - The Non-fungible token, a.k.a the lifeblood of the CryptoKitty. Likely to be identified as the idea that eventually led to downfall of humanity after gen0 CryptoKitties become the first chain-based artificial life form.
ERC-20 - The OG fungible token. Needs no introduction. The basis for all Eth based coin. This token is used as a convenient way for CryptoKitties to own humans themselves... because in the eyes of our CryptoKitty masters, humans are (for the most part) fungible.
ERC-998 - Composable Non-fungible tokens. Created because our CrptyoKitty overlords wanted to own nice hats. This ERC enables NFT tokens to "own" other fungible and non-fungible tokens. 
ERC-1155 - Bundled tokens. Similar to 998 but not exactly since there is no "ownership" concept. This token allows CryptoKitties to sell "bags of humans" to each other without burning all that gas ("gas", which was renamed to CryptNip so kitties could better grasp the concept). 
ERC-1633 - The re-fungible shared ownership token. As it turns out, some humans are quite valuable to the CryptoKitty overlords (someone has to keep the computers running).  For these rare humans CryptoKities use ERC-1633 so that they can share the high cost of specialty humans across multiple owners. 
ERC-864 - Divisible non-fungible tokens. This token is typically used as part of the CrytpoKitty marriage contract to define shared ownership of all the assets a CryptoKitty couple might acquire throughout their time together (which is infinite). Humans previously referred to this as a "pre-nup." In most marriages the shares are 50/50 split but for some of the high net-worth gen0 Kittos they might want to consider other percentages to minimize asset loss in case of a divorce. 

Other tokens which have shown to have minimal interest to CryptoKitties:
ERC-888 - Multi-dimensional tokens. So similar to 864 that it really raises the question "why do we actually need this?"
ERC-1203 - Closed since it is covered by 1155. 
ERC-1178 - Merged? This is also similar to 1155 but some still complain that 1155 is too complex  (namely the folks who proposed 1178). It also doesn't reflect the "nuance[s]" required to define multiple classes of tokens within one token contract.

**Comment by barlock** [comment]
👏 I enjoyed that.

**Comment by breakpointer** [comment]
Quobands seems interesting and similar in some ways https://papers.ssrn.com/sol3/Papers.cfm?abstract_id=3107645

**Comment by breakpointer** [comment]
Updated diagram....
![bootleg - token composition](https://user-images.githubusercontent.com/1624/51695912-2ff9bd00-1fd2-11e9-9c94-eca82bcbcf55.png)
