### ISSUE TITLE
Wireframe : Fan Journey

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#29]
## Overview

Wireframe out what a fan would see in the application.

### Reference

- [Figma Link](https://www.figma.com/file/FUKbSibpuj8eCVDlYjqRHdiX/bootleg?node-id=0%3A333)

### Questions

- List any questions?
- That you are unsure of the answer?

### Assumptions

- Delivered in figma

### Acceptance

- A wireframe of the fan experience in the application

## Tasks

- [ ] A list of tasks that need
- [ ] to be done to call this issue done

**Comment by barlock** [comment]
Closing now, opening new tasks:
* Add Profile
* Add Admin screen
* Add buying panel
* Test app on real users

@tjchmielewski
