### ISSUE TITLE
Learn the technical details of how video watermarking works

### ISSUE THREAD

**Issue by hadasz** [ConsenSys/web3studio-bootleg#39]
## Overview

It is important for this project for me to know the technical details of how video watermarking works. I would also like to relay the proof that someone can't remove the watermark in lay-mans terms.  

### Reference

- [Reference](links)
- [To issues](or-any-inspiration)
- [That might be](helpful)

### Questions

-How does it work?

### Assumptions

- I assume with some research, I will be able to understand and explain the technical details of how watermarking videos work

### Acceptance

- For this to be done, I have written something up about how it works, and explained why it is very hard for somebody to remove it

## Tasks
-Figure out how it works
-Write up how it works
-Write up about the proof and why its hard for someone to remove the watermark

**Comment by breakpointer** [comment]
@hadasz I'm assuming this is completed and am closing the issue.
