### ISSUE TITLE
Non-Transferability Technical Design/Document

### ISSUE THREAD

**Issue by hadasz** [ConsenSys/web3studio-bootleg#42]
## Overview

As a non-transferable asset implementer, I want to have a design and architecture, so I have a clear picture and understanding of what to build.

### Questions

- What is the best way to implement this?
- What should be left out? What should be included?

### Assumptions

- There is a way to implement something in the timeline we have

### Acceptance

- A descriptive technical document that will serve as a map.
- Diagrams explaining the architecture  

## Tasks

- Figure out what can be implemented
- Figure out overview of how to implement iti
- write it down

**Comment by breakpointer** [comment]
I'll help out with this and we'll work together to close this out today.

**Comment by breakpointer** [comment]
Document is attached and included below in the LucidCharts diagrams for bootleg (team members should all have full access)

https://www.lucidchart.com/invitations/accept/ba1933c9-82e4-4c23-ae0e-557f986cfa7d
![Bootleg - Encryption Diagram.png](https://images.zenhubusercontent.com/5c1837597d7e6b6f82e3250e/9558d8c9-6408-4348-b59e-8bf3e3dbbe95)
