### ISSUE TITLE
Task: UX Testing Brainstorm

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#44]
## Overview

As an owner of a bootleg company, I can understand how my app works with users, so that I can encourage use.

reach out to music and fan community to see if our assumptions are correct and how they feel about the prototype.

### Questions

- Does the user experience for the app tell the story without more information?
- Will industry executives be able to intuitively understand the story with just the app?
    - Can a ticket master of a company who might want to do a bootleg know all the angles from the app?

### Assumptions

- It's a meeting

### Acceptance

- Agreed experiment design and plan of action for UX testing

## Tasks
- [x] decide type of test(s) to perform
- [x] decide incentive
- [x] strategize on how to find participants

**Comment by humbitious** [comment]
Test is zoom-based concept testing. Let users go through the UX screens and tell us what they think this is and what the value is.  Watch for "hair on fire" moment or moments of confusion and/or "meh". Then analyze potential causality and refactor.

Using outside design resource still on the table but current course and speed is to get our own set of guinea pigs and do the sessions ourselves.

**Comment by mgw-sbic** [comment]
We would be interested in being part of the Zoom testing.
