### ISSUE TITLE
Bootleg DevKit : Outline

### ISSUE THREAD

**Issue by tjchmielewski** [ConsenSys/web3studio-bootleg#45]
## Overview

Understand what content we plan on distributing and how we are prioritizing and structuring it. 

### Reference

- [Brian's Outline](https://github.com/ConsenSys/web3studio-bootleg)
- [Barlock's mural board] #78 
- First Draft #52

### Questions

- Do we have enough content to get started?

### Assumptions

- Using outline template from #52

### Acceptance

- Follows template in #52
- is easy to understand and act on
- reviewed with team

## Tasks

- [ ] create outline
- [ ] review with team

**Comment by humbitious** [comment]
https://docs.google.com/document/d/1WtjXk0fz8IkksTzKXxSgjH5NxrANNTiQtTTc23dfaYM/edit#
