### ISSUE TITLE
Contract (token & application) Architecture diagrams

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#78]
## Overview

As a developer building or viewing the devkit, I can understand contract interactions and integration points, so that I can gain a better understanding of the contract backend.

### Acceptance

- Readme docs with 
    - Token architecture
    - contract interfaces
    - Namespace glossary
- state diagram token lifecycle
- sequence diagram – all actors & systems

**Comment by barlock** [comment]
Living mural of my current contract interface thinking: https://app.mural.co/t/consensys3989/m/consensys3989/1549562147271/3679eca807e7244ac40c4445a1eff72255219c01

**Comment by mgw-sbic** [comment]
Hey Michael,

How do I view your mural?

I'm using this email for the mural account.

Thank you!

All the best!
Michael Glenn Williams
CEO SmartBlonde Experiential Corp (SBEX)
President Smart Blonde Corp (Productions)
805.499.1994
www.smartblondeexperiential.com

**Comment by breakpointer** [comment]
Link to source diagrams is here https://www.lucidchart.com/documents/view/c887fd5a-2ee9-4bfb-92cc-00b237461054

**Comment by mgw-sbic** [comment]
Thank you this opened just fine and looks great.

Michael Glenn Williams
CEO SmartBlonde Experiential Corp (SBEX)
President Smart Blonde Corp (Productions)
805.499.1994
www.smartblondeexperiential.com
