### ISSUE TITLE
 Create withdrawal SharedRoyaltyToken interface

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#90]
## Overview

As a developer implementing a shared royalty token, I want to know I'm using best practices so that I don't break users (increasing gas costs) and ensure security (no reentrancy)

### Reference

- [Reentrancy topic](https://consensys.github.io/smart-contract-best-practices/known_attacks/#reentrancy)
- [Common Patterns](https://solidity.readthedocs.io/en/latest/common-patterns.html#withdrawal-from-contracts)

### Questions

- Are there any known ERC standards for contract withdrawals?
- Can we calculate balance at withdrawal time?
- How do we handle rounding errors?

### Acceptance

- Documented contract withdrawal pattern is written as a contract interface with NatSpec documentation (here)
- Documented questions are answered

## Tasks

- [ ] Research existing ERCs and prior art
- [ ] Document results and proposed interface

**Comment by barlock** [comment]
Notes:

OpenZeppelin has an [escrow contract](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/payment/escrow/Escrow.sol) that we can/should use to handle the escrow for the token. We can expose it's api via ours.

Rounding errors doesn't really seem to be an issue (??) as the math is handled in wei. Viewing OpenZeppelin's [Payment Splitter](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/payment/PaymentSplitter.sol#L86), they don't make any special cases for handling it. 

For understanding, if we can calculate balance at withdrawal time:

I wrote a tiny script to run a test scenario of splitting every payment by the number of franchisors. The gas cost per transaction follows this formula (except index 0, which spikes a bit) `gasUsed = 7781 * franchisorIndex + 63135`

There is a [max gas limit](https://ethstats.net/) around 8mil, that means our token can be sold a **max number of ~7,000,000 times**. The max cost in tx fees (assuming current USD market value and a gas price of 4Gwei) is **~$3.80**.

☝️ That's not as bad as I was guessing. It's not amazing if we're assuming we could have a single digital asset (an album) that gets distributed via everyone who's owned it with the rights to sell an unlimited number of times (ie, a single token representing a single album). 

I'm going to take another think about HMW make transfer's a fixed gas price while withdrawals increase with the number of transactions or amount that can be withdrawn.

**Comment by barlock** [comment]
@breakpointer What do you think about my assumptions here?

**Comment by breakpointer** [comment]
Seem solid to me; rounding errors handled, escrow seems like the right approach here, 7 million is plenty of headroom for transactions on one asset. 👍

**Comment by barlock** [comment]
Bah, I did the math wrong, max of 1020. Editing original post.

**Comment by barlock** [comment]
I'm not looking forward to implementing this. Here's hoping some other lucky person gets to! 

The payment proposed above does payment calculation and distribution at transfer time, this means gas prices for transfer are linear. Ideally, it would be fixed.

Some operation that **can be broken up** needs to be linear so that it's possible to have (virtually) unlimited franchisors, and all franchisors can get all of the Eth they're owed. What I believe this to mean is that the only place to do the expensive calculations is at withdraw-time and withdraw needs to be able to limit the number of withdrawals by the gas expense. 

I can see two different apis to do this, one more ux friendly, the other more dev friendly. I'll document below, bear in mind that for both, the following new things must be true.

- Withdrawals happen per 721, you cannot withdraw all earnings from all tokens at once, at least at the 721 level. (upstream contracts could iterate over all of them)
- Every token keeps track of a stream of payments, it's own transaction history `uint[] payments`
- Withdrawals will need to keep track of which payments have been withdrawn for each franchisor to ensure no double payments
- each "style" will need to implement a `paymentBalanceOf(tokenId, franchisor, paymentStart, paymentEnd)` function that, for any token franchisor, and range of payments, calculates what that franchisor is owed. This will become complicated with cycles of franchisors (think a franchisor selling the token to themselves)

The two different withdrawl patterns are:
* (Better for devs) withdrawals are paged by the user with a `count` that starts where they last withdrew from, and goes to the end. If they give too high of a count, it will revert and they'll need to try again
* (Better for users) withdraw transfers the most amount it can given the gas provided. returns `true` if done, or `false` if there is still more to withdraw. This will require the function to know how much gas calculating a balance is and can use `gasLeft()` to make sure it has enough to send the eth after. This seems tricky and I think the top one is better for a first pass at the very least as the balance calculation could vary a lot and might not be linear.

I'm assuming a "real" app would be able to streamline this whole withdrawal thing so the user never sees it anyway. Interface coming next.

**Comment by barlock** [comment]
The interface! A few notes. The "escrow" contract linked in the previous comment no longer applies. I still like the pattern and a custom one could be used in an implementation (a SharedRoyaltyEscrow anyone?) but that shouldn't affect the exposed abi. 

Without further ado:

```sol
  /**
   * @notice Withdraws payment accumulated from transfer of a given token from
   *  the last withdrawn payment up to a _count

   * @param _tokenId The identifier for an NFT
   * @param _count The number of payments to traverse
   */
  function withdrawPayment(uint256 _tokenId, uint256 _count) external;

  /**
   * @notice Withdraws non-withdrawn payment accumulated from transfer of a
   *   given token
   * @dev Escrow should keep track of the payments that have been processed to
   *   avoid double withdrawals
   *
   * @param _tokenId The identifier for an NFT
   */
  function withdrawPayment(uint256 _tokenId) external;

  /**
   * @notice Gets balance of non-withdrawn payment accumulated from transfer of a
   *   given token up to a number of provided payments
   * @dev Used by `withdrawPayment` to calculate how much a franchisor is owed.
   * @dev Implement this function to
   *
   * @param _tokenId The identifier for an NFT
   * @param _start The payment index to start from
   * @param _count The number of payments to traverse
   */
  function paymentBalanceOf(uint256 _tokenId, uint256 _start, uint256 _count) public;

  /**
   * @notice Gets balance of non-withdrawn payment accumulated from transfer of a
   *   given token that has not been withdrawn
   *
   * @dev Defaults to overloaded `withdrawPayment` of a token's non-withdrawn balance
   *   to the last payment
   * @dev Used by `withdrawPayment` to calculate how much a franchisor is owed.
   *
   * @param _tokenId The identifier for an NFT
   */
  function paymentBalanceOf(uint256 _tokenId) public;
```

**Comment by breakpointer** [comment]
@barlock WRT "withdrawals are paged" Could you provide an example of the data structure you have in mind here? I thought we could have a simple balance (single float) to store what a franchisor would be owed at any given time. During the transfer transaction when eth is distributed we would be crediting those balances with a fixed rate * sale price.

**Comment by barlock** [comment]
> I thought we could have a simple balance (single float) to store what a franchisor would be owed at any given time.

That was my original attempt and a clean solution. With that approach, you need to calculate the balance when a `transfer` happens. Given our "brain dead simple" model of equal royalties (the code in the original post), it limited the number of transfers to 1k. I don't believe that to be large enough for our purposes. 

My second attempt, the one here, tries to perform that calculation at withdraw time rather than deposit time. A rough attempt in code below, the data structure for the escrow will likely change but hopefully it will get the idea across.

I realized when writing this that the 


```sol


struct Token {
  uint256[] payments;
  address[] franchisors;
  mapping(address => uint256) franchisorLastWithdrawIndex;
}


mapping (uint256 => Token) public tokens;

function transfer (uint256 _tokenId, address payable _newOwner) {
  Token token = tokens[_tokenId];

  token.franchisors.push(_newOwner);
  token.payments.push(msg.value);
}

function withdraw (uint256 _tokenId, uint256 _count) {
  // Payment balance of is implemented per style, so bookened would calculate this 
  // sender's balance (I realized now that maybe the api should specifiy which payee, need to check prior art) 
  // based on the `payments` array, start, and count
  uint256 withdrawBalance = this.paymentBalanceOf(
    _tokenId, 
    token.franchisorLastWithdrawIndex[msg.sender], 
    _count
  );

  msg.sender.transfer(withdrawBalance);
}

function withdraw (uint256 _tokenId) {
  Token token = tokens[_tokenId];

  this.withdraw(_tokenId, token.payments.length); 
}
```
