### ISSUE TITLE
Build Demo Web App

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#99]
## Overview

As a person learning about the bootleg token I want a demo app that I can buy the worlds first 😍 shared royalty token, so that wow, such excite, many shared royalties!

### Assumptions

- The app is as simple as possible (oneclickdapp.com is possible if it can be edited)

### Acceptance

- There is a simple web application that:
- Allows for purchase a PIB Token
- For those that have ever owned a PIB token, download its video asset
  - Originally, it might say coming soon as the video asset won't exist until after the event.
- The web application should be deployed at `consensys.net/web3studio/bootleg/<demo|purchase|??>`
    - We probably should open source the website code so we can link there...
- The application will only be up and running during the limited trading ceremony for the first bootleg token

## Address these concerns
- [ ] All transfers are in eth and not wei (wei is way hard for humans)
- [ ] instead of 'setting price' users actions is 'list for sale' (with a call to set price under the hood)

Rough UI structure...
![Bootleg trader app UI](https://user-images.githubusercontent.com/1624/57038065-f9fa5380-6c26-11e9-9536-d6bec7fdd3c0.png)

**Comment by breakpointer** [comment]
Potentially we could use this https://oneclickdapp.com/tourist-unicorn/

**Comment by breakpointer** [comment]
Demo app trading script/support document https://docs.google.com/document/d/1Fx8dQpUCHRiUWmd8_2EbC1-rfTudd45uO8wJ7kaVizQ/edit?usp=sharing
